development:
  adapter: postgresql
  encoding: unicode
  database: development_billionaire
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: test_billionaire
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: production_billionaire
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
